spring.application.name=spring_security

spring.security.user.name= rohan
spring.security.user.password= bulbul

spring.datasource.url=jdbc:postgresql://localhost:5432/springSecurity
spring.datasource.username=postgres
spring.datasource.password=admin

